### ISSUE TITLE
viz.bar word spacing wrong when groupBy used

### ISSUE THREAD

**Issue by dfilan** [probmods/webppl-viz#24]
viz.bar seems to treat strings on the x-axis differently when the groupBy option is used. The following two function calls result in the words "absolutely" and "positively" rotated on the x-axis, allowing for easy legibility:

```
var myData = [{x: 'absolutely', y: 2}, {x: 'positively', y: 3}];
viz.bar(myData);
viz.bar(['absolutely', 'positively'], [2,3]);
```

However, the following code has the words "absolutely" and "positively" horizontally positioned and overlapping with each other:

```
var myData = [{x: 'absolutely', y: 2, c: 'a'}, {x: 'positively', y: 3, c: 'a'}];
viz.bar(myData, {groupBy: 'c'});
```

**Comment by longouyang** [comment]
Should be fixed now
