### ISSUE TITLE
Make webppl-viz compatible with new distribution interface

### ISSUE THREAD

**Issue by stuhlmueller** [probmods/webppl-viz#26]
For example, this doesn't work:

``` js
var result = Infer({method: 'MCMC', samples: 100}, function(){
  return uniform(0, 1);
});

viz.auto(result);
```

A possible cause is that `webppl-viz` makes calls of the form `foo.score(null, val)` instead of `foo.score(val)`.

**Comment by longouyang** [comment]
a8c6870 should address this -- can you test?

**Comment by longouyang** [comment]
actually, try 2450784

**Comment by stuhlmueller** [comment]
Works, thanks!
