### ISSUE TITLE
Directly visualize continuous distributions

### ISSUE THREAD

**Issue by stuhlmueller** [probmods/webppl-viz#27]
Example:

``` js
var myBeta = Beta({a: 1, b: 1});
viz.auto(myBeta)
```

Currently, this fails with message `support.map is not a function`.

**Comment by longouyang** [comment]
Methods that operate on dists currently assume that the support is an array; we'd need to modify things to work on the object supports of continuous distributions.

**Comment by longouyang** [comment]
Some progress in 590220a; we now can handle things like `Gaussian`, `Beta`, and tensor-valued things like `Dirichlet`.

`Poisson` needs some work though.

**Comment by longouyang** [comment]
Added a dumb fix for Poisson in 6209f32 (just clip the domain to `{0, ..., 10}` and inform the user that we're doing this for viz purposes)
