### ISSUE TITLE
Requiring package causes stuff to be logged to the console

### ISSUE THREAD

**Issue by chrisranderson** [probmods/webppl-viz#44]
Just by requiring the package, I get this logged to the console when I run my script:

```
{
 "skill": "x",
 "country": "facetCol",
 "group": "color"
}
{
 "skill": "x",
 "country": "facetCol",
 "group": "facetRow"
}
{
 "skill": "x",
 "group": "facetCol",
 "country": "color"
}

...etc
```

Also, a dumb question: calling `viz.*` gives me `viz is not defined`. Is a different variable exposed?

**Comment by longouyang** [comment]
I fixed the `viz not defined` issue in 667b672 (using `webpplViz` would have worked, but it's nicer to be able to just use `viz` on both browser and cli).

And I fixed the logging stuff in 91c3537 (I've been working on some newer fancy stuff the past few days and the repo has been in a little bit of a hairy state).

More generally -- bear with us as the PPAML summer school approaches (we'll be moving pretty fast and breaking stuff pretty fast)

**Comment by chrisranderson** [comment]
No worries! Good luck with the next few days, I bet it's kinda crazy.

Want a hand with something? I can work on docs for all the functions in the
header file, or maybe there is something more pressing that I could be
productive with.

If it helps me prepare for the summer school I don't  feel too bad working
on it at work.

**Comment by longouyang** [comment]
We'd appreciate any help you could spare!

Header docs might be the easiest place to help out right now -- I'm actually not sure what the status of that is, so maybe ping Paul (@null-a).

**Comment by null-a** [comment]
We now have basic docs for lots of the header, [here for example](http://docs.webppl.org/en/master/arrays.html). The plan is to gradually improve these over time. Any PRs that do so will be welcome!

There are a few issues from [the current milestone](https://github.com/probmods/webppl/milestone/3) up for grabs. Of those, #326 is probably the most approachable. There are also other [documentation issues](https://github.com/probmods/webppl/issues?q=is%3Aopen+is%3Aissue+label%3Adocumentation) you might look at if that's something of interest to you. Feel free to comment on any other issues you're considering working on but could use pointers for before getting started. I'm happy to try and pick out a few candidate issues if you'd like.

**Comment by chrisranderson** [comment]
Ones I was thinking about:
- I could handle the small change Noah mentioned: https://github.com/probmods/webppl/issues/443
- Moving these to the site: https://github.com/probmods/webppl/issues/394 on this page: http://docs.webppl.org/en/master/packages.html
- maybe some type of editorial run through of all of the docs
- getting all the header.wppl functions documented

I have time until the 20th to help, so feel free to put me to work. :)

**Comment by null-a** [comment]
> so feel free to put me to work. :)

They all sound pretty reasonable to me, go for it! My only advice would be 1) keep any PRs reasonably small so that they are easy to review and 2) maybe comment on issues you're working on so we avoid duplicating effort.

Short PRs will be particularly useful while folk are busy with prep for the summer school. This might make point 3 on your list tricky, depending what you have in mind.

Let's move any further discussion of this elsewhere so we're not cluttering up this (unrelated) issue. The mailing list or specific issues will probably work.
