### ISSUE TITLE
Hist leaves out x-axis values

### ISSUE THREAD

**Issue by cscherrer** [probmods/webppl-viz#54]
In the ["Hiking with Stochastic Transitions" section](http://agentmodels.org/chapters/3b-mdp-gridworld.html) of the PPAML summer school, `viz.auto` sometimes produces histograms like this:
![viz auto](https://cloud.githubusercontent.com/assets/1184449/17339949/100ba66e-58a3-11e6-8555-aec747d4463f.png)

"State" values are integers, so we'd (or at least I'd) expect in-between values to be included on the axis (even for zero counts).

**Comment by longouyang** [comment]
Thanks for the report.

Right now viz applies some simple heuristics to detect the type of a variable (categorical versus real).

Currently we don't have a good interface for giving hints about variables (e.g., type, bounds, support) but this is on my todo list.

**Comment by longouyang** [comment]
Fixed in 3430c6a -- we now treat integers as real numbers.

Eventually, we probably want to do some special things for integers, though.
