### ISSUE TITLE
viz.auto inappropriately plots densities for distributions with integer support

### ISSUE THREAD

**Issue by hawkrobe** [probmods/webppl-viz#60]
e.g. 

```
viz(Binomial({p: .5, n: 5}))
```

**Comment by longouyang** [comment]
A basic fix is in 6209f32, which handles integer supports for the univariate case (but not any higher dimensionality cases).

Even this took basic fix me a while to implement, as the library has become really hamstrung by early architectural choices. So I'm going to freeze development for now and focus on the big overhaul.
