### ISSUE TITLE
viz.auto() doesn't know how to render Gaussian({ mu: 0, sigma: 1 })

### ISSUE THREAD

**Issue by critcha** [probmods/webppl-viz#67]
Is the intended behavior of

`viz.auto(Gaussian({mu: 0, sigma:1}))`

to return a probability density function?  It returns the error in the title instead...

**Comment by longouyang** [comment]
Looks like there's some bug with `viz.auto`. For now, use `viz`, which is a wrapper around `viz.auto`: `viz(Gaussian({mu: 0, sigma:1}))`

**Comment by critcha** [comment]
Thanks dude!

**Comment by longouyang** [comment]
Fixed
