### ISSUE TITLE
what is the best way to  to istall the package webppl-viz on tbest/beacker-webppl

### ISSUE THREAD

**Issue by krylov48** [probmods/webppl-viz#80]
how can I install webppl-vz on the Beacker Notebook tbenst/beacker-webppl if have deploed docker image? Can I install any package from Beacker Notebook page directly no command line?

**Comment by longouyang** [comment]
I'm not sure -- @tbenst do you have any ideas?

**Comment by tbenst** [comment]
What you can do right now is use Webppl for computation, and R or Python for plotting, leveraging the Beaker Object for conversion between languages as shown in the Webppl-Beaker example. Happy to write a simple histogram example with webppl & matplotlib if helpful.

## Plotting client-side
Beaker has a simple [plot API](https://github.com/twosigma/beakerx/wiki/Plot-JSON-Specification) that could be used [Javascript example](https://github.com/twosigma/beakerx/wiki/Create-a-Plot-from-Different-Languages). Also may be possible to take the result from the client, and plot using browser webppl-viz: https://github.com/twosigma/beakerx/wiki/Create-an-OutputDisplay

## Plotting host-side
Here's the [main part](https://github.com/tbenst/beaker-webppl/blob/master/plugin/webppl/src/dist/app/app.js) of the Webppl plugin implementation. If it's possible to output a webppl-viz jpeg to a file, it should be possible to send & display it client-side.
