### ISSUE TITLE
viz.print interaction plots have giant dots for high-probability events

### ISSUE THREAD

**Issue by stuhlmueller** [probmods/webppl-viz#9]
`viz.print` creates interaction scatterplots with dot sizes that reflect the probability of the corresponding joint events. For likely events, this creates giant dots. Compare:

This works, sort of:

```
viz.print(Enumerate(function(){
  return {
    "a": flip(.6) ? 0 : 1,
    "b": flip(.7) ? 0 : 1,
    "c": flip(.8) ? 0 : 1
  }
}))
```

This looks unreadable:

```
viz.print(Enumerate(function(){
  return {
    "a": flip(.9) ? 0 : 1,
    "b": flip(.9) ? 0 : 1,
    "c": flip(.99) ? 0 : 1
  }
}))
```

**Comment by longouyang** [comment]
`viz.print` is Erin's method, which I'm not working on and am only keeping around until I get my version (currently called `viz.vegaPrint`) up to feature parity.

I'll be sure to fix this in my version, though, once I write the plotter for real x real plots.
